apiVersion: v2
name: flextime
description: A Helm chart for Flextime scheduling application
type: application
version: 1.0.0
appVersion: "1.0.0"

maintainers:
  - name: XII-Ops Team
    email: ops@big12sports.com

keywords:
  - scheduling
  - sports
  - big12
  - flextime

home: https://flextime.big12sports.com
sources:
  - https://github.com/big12/flextime

dependencies:
  - name: postgresql
    version: "12.1.9"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.4.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: nginx-ingress
    version: "4.4.2"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress.nginx.enabled

annotations:
  category: Application
  licenses: MIT