# Docker Compose Override for Development
# This file is automatically loaded by docker-compose in development

version: '3.8'

services:
  backend:
    build:
      target: development
    environment:
      NODE_ENV: development
      DEBUG: "flextime:*"
      LOG_LEVEL: debug
    volumes:
      # Mount source code for hot reload
      - ./backend:/app/backend
      - /app/backend/node_modules
    command: sh -c "cd /app/backend && exec node app.js"

  frontend:
    build:
      target: development
    environment:
      NODE_ENV: development
      REACT_APP_DEBUG: "true"
    volumes:
      # Mount source code for hot reload
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    command: sh -c "cd /app/frontend && python3 -m http.server 3000"

