version: '3.8'

services:
  backend:
    env_file:
      - ./backend/.env
    environment:
      - REDIS_URL=redis://redis:6379
  
  frontend:
    environment:
      - REACT_APP_API_URL=http://localhost:3001
