cluster.name: flextime-monitoring
node.name: elasticsearch-01
network.host: 0.0.0.0
http.port: 9200

# Discovery
discovery.type: single-node

# Security
xpack.security.enabled: true
xpack.security.enrollment.enabled: true
xpack.security.http.ssl:
  enabled: true
  keystore.path: certs/http.p12
xpack.security.transport.ssl:
  enabled: true
  verification_mode: certificate
  keystore.path: certs/transport.p12
  truststore.path: certs/transport.p12

# Monitoring
xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true

# License
xpack.license.self_generated.type: basic

# Memory
bootstrap.memory_lock: true

# Paths
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# HTTP
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: "Authorization, Content-Type"

# Indices settings
indices.query.bool.max_clause_count: 10000

# Thread pools
thread_pool:
  search:
    size: 50
    queue_size: 1000
  write:
    size: 30
    queue_size: 500

# Circuit breakers
indices.breaker.total.use_real_memory: false
indices.breaker.total.limit: 85%
indices.breaker.request.limit: 60%
indices.breaker.fielddata.limit: 40%

# Logging
logger.level: INFO