apiVersion: v1
kind: Secret
metadata:
  name: flextime-secrets
  namespace: flextime
  labels:
    app: flextime
    component: secrets
type: Opaque
stringData:
  # These should be populated by your CI/CD pipeline or external secret management
  database-url: "postgresql://username:password@database-host:5432/flextime"
  redis-url: "redis://redis-host:6379"
  jwt-secret: "your-jwt-secret-here"
  notion-api-key: "your-notion-api-key-here"
  
  # Additional secrets for various integrations
  aws-access-key-id: "your-aws-access-key-id"
  aws-secret-access-key: "your-aws-secret-access-key"
  
  # Email configuration
  smtp-host: "smtp.office365.com"
  smtp-port: "587"
  smtp-username: "your-email@big12sports.com"
  smtp-password: "your-email-password"
  
  # External API keys
  google-api-key: "your-google-api-key"
  microsoft-graph-client-id: "your-microsoft-graph-client-id"
  microsoft-graph-client-secret: "your-microsoft-graph-client-secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: flextime-staging-secrets
  namespace: flextime-staging
  labels:
    app: flextime
    component: secrets
    environment: staging
type: Opaque
stringData:
  database-url: "postgresql://username:password@staging-database-host:5432/flextime_staging"
  redis-url: "redis://staging-redis-host:6379"
  jwt-secret: "staging-jwt-secret-here"
  notion-api-key: "staging-notion-api-key-here"
---
apiVersion: v1
kind: Secret
metadata:
  name: flextime-prod-secrets
  namespace: flextime-prod
  labels:
    app: flextime
    component: secrets
    environment: production
type: Opaque
stringData:
  database-url: "postgresql://username:password@prod-database-host:5432/flextime_prod"
  redis-url: "redis://prod-redis-host:6379"
  jwt-secret: "production-jwt-secret-here"
  notion-api-key: "production-notion-api-key-here"