# Development environment values for Flextime

replicaCount:
  backend: 1
  frontend: 1
  worker: 1

image:
  backend:
    repository: ghcr.io/big12/flextime
    pullPolicy: Always
    tag: "develop-backend"
  frontend:
    repository: ghcr.io/big12/flextime
    pullPolicy: Always
    tag: "develop-frontend"
  worker:
    repository: ghcr.io/big12/flextime
    pullPolicy: Always
    tag: "develop-worker"

resources:
  backend:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  frontend:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  worker:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

autoscaling:
  enabled: false

ingress:
  enabled: true
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health
  hosts:
    - host: dev.flextime.big12sports.com
      paths:
        - path: /api
          pathType: Prefix
          service: backend
        - path: /
          pathType: Prefix
          service: frontend
  tls: []

env:
  NODE_ENV: development
  LOG_LEVEL: debug
  CACHE_TTL: 60

# External dependencies
postgresql:
  enabled: true
  auth:
    postgresPassword: "dev-postgres-password"
    username: flextime
    password: "dev-flextime-password"
    database: flextime_dev
  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: gp2

redis:
  enabled: true
  auth:
    enabled: true
    password: "dev-redis-password"
  master:
    persistence:
      enabled: true
      size: 4Gi
      storageClass: gp2

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 30s

networkPolicy:
  enabled: false

podDisruptionBudget:
  enabled: false