apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flextime.fullname" . }}
  labels:
    {{- include "flextime.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "flextime.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "flextime.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "flextime.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.config.port }}
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          {{- if .Values.healthCheck.enabled }}
          livenessProbe:
            {{- toYaml .Values.healthCheck.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.healthCheck.readinessProbe | nindent 12 }}
          {{- end }}
          env:
            - name: NODE_ENV
              value: {{ .Values.app.config.nodeEnv }}
            - name: LOG_LEVEL
              value: {{ .Values.app.config.logLevel }}
            - name: PORT
              value: {{ .Values.app.config.port | quote }}
            - name: WORKERS
              value: {{ .Values.app.config.workers | quote }}
            {{- if .Values.postgresql.enabled }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "flextime.fullname" . }}-secret
                  key: database-url
            {{- else if .Values.postgresql.external.host }}
            - name: DB_HOST
              value: {{ .Values.postgresql.external.host }}
            - name: DB_PORT
              value: {{ .Values.postgresql.external.port | quote }}
            - name: DB_NAME
              value: {{ .Values.postgresql.external.database }}
            - name: DB_USER
              value: {{ .Values.postgresql.external.username }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.external.existingSecret }}
                  key: {{ .Values.postgresql.external.secretKeys.passwordKey }}
            {{- end }}
            {{- if .Values.redis.enabled }}
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "flextime.fullname" . }}-secret
                  key: redis-url
            {{- else if .Values.redis.external.host }}
            - name: REDIS_HOST
              value: {{ .Values.redis.external.host }}
            - name: REDIS_PORT
              value: {{ .Values.redis.external.port | quote }}
            {{- if .Values.redis.external.existingSecret }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.external.existingSecret }}
                  key: {{ .Values.redis.external.secretKeys.passwordKey }}
            {{- end }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "flextime.fullname" . }}-config
            - secretRef:
                name: {{ include "flextime.fullname" . }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /app/.cache
      volumes:
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}