---
- name: Set timezone
  timezone:
    name: "{{ timezone | default('UTC') }}"

- name: Install common packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - htop
    - curl
    - wget
    - git
    - python3-pip
    - python3-dev
    - build-essential
    - unzip
    - jq
    - net-tools
    - telnet
    - ntp

- name: Configure NTP
  service:
    name: ntp
    state: started
    enabled: yes

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
    state: present

- name: Configure sysctl parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - { key: 'net.core.somaxconn', value: '65535' }
    - { key: 'net.ipv4.tcp_max_syn_backlog', value: '65535' }
    - { key: 'net.ipv4.ip_local_port_range', value: '1024 65535' }
    - { key: 'net.ipv4.tcp_tw_reuse', value: '1' }
    - { key: 'vm.swappiness', value: '10' }

- name: Configure logrotate
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/flextime
    owner: root
    group: root
    mode: '0644'

- name: Create application user
  user:
    name: "{{ app_user }}"
    shell: /bin/bash
    home: "/home/{{ app_user }}"
    createhome: yes
    groups: sudo
    append: yes

- name: Set up SSH key for app user
  authorized_key:
    user: "{{ app_user }}"
    key: "{{ lookup('file', 'files/flextime-deploy.pub') }}"
    state: present