apiVersion: v1
kind: Namespace
metadata:
  name: flextime-agents
  labels:
    name: flextime-agents
    app.kubernetes.io/name: flextime
    app.kubernetes.io/component: microservices
    app.kubernetes.io/version: "1.0.0"
  annotations:
    description: "Namespace for FlexTime Agent Microservices"
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: flextime-agents-quota
  namespace: flextime-agents
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "50"
    services: "20"
    persistentvolumeclaims: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: flextime-agents-limits
  namespace: flextime-agents
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim