# Baseline Load Test Scenario
# Tests normal expected load conditions

name: "Baseline Load Test"
description: "Simulates normal daily traffic patterns"

stages:
  - duration: 2m
    target: 50
    description: "Ramp up to 50 users"
  - duration: 5m
    target: 50
    description: "Maintain 50 users"
  - duration: 2m
    target: 0
    description: "Ramp down to 0 users"

thresholds:
  - metric: http_req_duration
    threshold: p(95)<500
    description: "95% of requests should be under 500ms"
  - metric: http_req_failed
    threshold: rate<0.01
    description: "Error rate should be below 1%"
  - metric: http_reqs
    threshold: rate>50
    description: "Should handle at least 50 requests per second"

scenarios:
  user_journey:
    exec: userJourney
    executor: ramping-vus
    stages:
      - duration: 2m
        target: 50
      - duration: 5m
        target: 50
      - duration: 2m
        target: 0

user_actions:
  - action: login
    weight: 10
  - action: viewDashboard
    weight: 30
  - action: createTimeEntry
    weight: 20
  - action: viewReports
    weight: 15
  - action: updateProfile
    weight: 5
  - action: searchProjects
    weight: 20