# Endurance Load Test Scenario
# Tests system stability over extended periods

name: "Endurance Load Test"
description: "Tests system stability over 2-4 hours"

stages:
  - duration: 10m
    target: 100
    description: "Ramp up to steady state"
  - duration: 2h
    target: 100
    description: "Maintain steady load"
  - duration: 10m
    target: 0
    description: "Ramp down"

thresholds:
  - metric: memory_leak_detection
    threshold: growth_rate<1MB/hour
    description: "Memory should not grow more than 1MB per hour"
  - metric: http_req_duration
    threshold: p(95)<500
    description: "95% of requests consistently under 500ms"
  - metric: database_connection_pool
    threshold: exhaustion_rate=0
    description: "No connection pool exhaustion"

monitoring:
  extended_metrics:
    - memory_usage_trend
    - gc_frequency
    - thread_count
    - file_descriptor_count
    - database_connection_lifecycle
    - cache_hit_ratio_stability
    - disk_space_usage
    - log_file_growth

leak_detection:
  - memory_profiling_interval: 15m
  - heap_dump_on_threshold: 80%
  - connection_tracking: enabled
  - resource_cleanup_validation: enabled