# Stress Load Test Scenario
# Tests system behavior under increasing load

name: "Stress Load Test"
description: "Gradually increases load to find breaking point"

stages:
  - duration: 2m
    target: 100
    description: "Ramp up to 100 users"
  - duration: 5m
    target: 100
    description: "Maintain 100 users"
  - duration: 2m
    target: 200
    description: "Increase to 200 users"
  - duration: 5m
    target: 200
    description: "Maintain 200 users"
  - duration: 2m
    target: 300
    description: "Increase to 300 users"
  - duration: 5m
    target: 300
    description: "Maintain 300 users"
  - duration: 5m
    target: 0
    description: "Ramp down to 0 users"

thresholds:
  - metric: http_req_duration
    threshold: p(95)<1000
    description: "95% of requests should be under 1s"
  - metric: http_req_failed
    threshold: rate<0.05
    description: "Error rate should be below 5%"
  - metric: http_reqs
    threshold: rate>100
    description: "Should handle at least 100 requests per second"

monitoring:
  - cpu_usage
  - memory_usage
  - database_connections
  - response_time_degradation
  - error_rate_increase

alerts:
  - condition: cpu_usage > 80%
    action: notify
  - condition: memory_usage > 85%
    action: notify
  - condition: error_rate > 5%
    action: scale_back