# Kubernetes namespaces for FlexTime environments
apiVersion: v1
kind: Namespace
metadata:
  name: flextime-production
  labels:
    name: flextime-production
    environment: production
    app: flextime
---
apiVersion: v1
kind: Namespace
metadata:
  name: flextime-staging
  labels:
    name: flextime-staging
    environment: staging
    app: flextime
---
apiVersion: v1
kind: Namespace
metadata:
  name: flextime-development
  labels:
    name: flextime-development
    environment: development
    app: flextime
---
# Resource quotas for production
apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-quota
  namespace: flextime-production
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "20"
---
# Resource quotas for staging
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: flextime-staging
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "5"
    services: "10"