# Scheduler Service Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-svc
  namespace: flextime-production
  labels:
    app: flextime
    component: scheduler-svc
    environment: production
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: flextime
      component: scheduler-svc
  template:
    metadata:
      labels:
        app: flextime
        component: scheduler-svc
        environment: production
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4000"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: scheduler-svc
        image: flextime/scheduler-svc:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          name: http
          protocol: TCP
        env:
        - name: SERVICE_NAME
          value: "scheduler-svc"
        - name: PYTHONPATH
          value: "/app/python"
        - name: OR_TOOLS_VERSION
          value: "9.7.2996"
        envFrom:
        - configMapRef:
            name: flextime-config
        - secretRef:
            name: flextime-secrets
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: scheduler-data
          mountPath: /app/data
        - name: logs
          mountPath: /app/logs
        - name: models
          mountPath: /app/models
      volumes:
      - name: scheduler-data
        persistentVolumeClaim:
          claimName: scheduler-data-pvc
      - name: logs
        emptyDir: {}
      - name: models
        persistentVolumeClaim:
          claimName: scheduler-models-pvc
      nodeSelector:
        kubernetes.io/os: linux
        node-type: compute-optimized
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300

---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-svc-service
  namespace: flextime-production
  labels:
    app: flextime
    component: scheduler-svc
spec:
  type: ClusterIP
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: flextime
    component: scheduler-svc

---
# PersistentVolumeClaim for scheduler data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scheduler-data-pvc
  namespace: flextime-production
  labels:
    app: flextime
    component: scheduler-svc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3

---
# PersistentVolumeClaim for ML models
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scheduler-models-pvc
  namespace: flextime-production
  labels:
    app: flextime
    component: scheduler-svc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: efs

---
# KEDA ScaledObject for event-driven scaling
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scheduler-svc-scaler
  namespace: flextime-production
spec:
  scaleTargetRef:
    name: scheduler-svc
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: redis
    metadata:
      address: redis-service:6379
      listName: scheduling_queue
      listLength: "5"
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-service:9090
      metricName: flextime_active_scheduling_jobs
      threshold: "2"
      query: sum(flextime_active_scheduling_jobs{service="scheduler-svc"})