# Secret templates for FlexTime services
# Note: These are templates - actual secrets should be managed via sealed-secrets or external secret management
apiVersion: v1
kind: Secret
metadata:
  name: flextime-secrets
  namespace: flextime-production
type: Opaque
stringData:
  # Database credentials (to be replaced with actual values)
  NEON_DB_CONNECTION_STRING: "postgresql://user:password@host:5432/database?sslmode=require"
  NEON_DB_HOST: "ep-cool-scene-123456.us-east-1.aws.neon.tech"
  NEON_DB_PORT: "5432"
  NEON_DB_NAME: "flextime_production"
  NEON_DB_USER: "flextime_user"
  NEON_DB_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  
  # API Keys (to be replaced with actual values)
  OPENAI_API_KEY: "sk-CHANGE_ME_IN_PRODUCTION"
  ANTHROPIC_API_KEY: "sk-ant-CHANGE_ME_IN_PRODUCTION"
  NOTION_API_KEY: "secret_CHANGE_ME_IN_PRODUCTION"
  
  # JWT Secret
  JWT_SECRET: "CHANGE_ME_IN_PRODUCTION_USE_STRONG_RANDOM_STRING"
  
  # Redis password (if required)
  REDIS_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  
  # External service credentials
  HELIIX_API_KEY: "CHANGE_ME_IN_PRODUCTION"
  MCP_API_KEY: "CHANGE_ME_IN_PRODUCTION"

---
apiVersion: v1
kind: Secret
metadata:
  name: flextime-secrets
  namespace: flextime-staging
type: Opaque
stringData:
  # Staging database credentials
  NEON_DB_CONNECTION_STRING: "postgresql://user:password@host:5432/database?sslmode=require"
  NEON_DB_HOST: "ep-staging-scene-789012.us-east-1.aws.neon.tech"
  NEON_DB_PORT: "5432"
  NEON_DB_NAME: "flextime_staging"
  NEON_DB_USER: "flextime_staging_user"
  NEON_DB_PASSWORD: "CHANGE_ME_IN_STAGING"
  
  # API Keys for staging
  OPENAI_API_KEY: "sk-CHANGE_ME_IN_STAGING"
  ANTHROPIC_API_KEY: "sk-ant-CHANGE_ME_IN_STAGING"
  NOTION_API_KEY: "secret_CHANGE_ME_IN_STAGING"
  
  # JWT Secret for staging
  JWT_SECRET: "CHANGE_ME_IN_STAGING_USE_DIFFERENT_KEY"
  
  # Redis password for staging
  REDIS_PASSWORD: "CHANGE_ME_IN_STAGING"
  
  # External service credentials for staging
  HELIIX_API_KEY: "CHANGE_ME_IN_STAGING"
  MCP_API_KEY: "CHANGE_ME_IN_STAGING"

---
# TLS Secret template for HTTPS
apiVersion: v1
kind: Secret
metadata:
  name: flextime-tls
  namespace: flextime-production
type: kubernetes.io/tls
data:
  # Base64 encoded TLS certificate and key
  # Replace with actual certificate data
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...