---
- name: Configure Flextime Infrastructure
  hosts: all
  become: true
  gather_facts: true
  
  vars_files:
    - "vars/{{ environment }}.yml"
    - "vars/secrets.yml"
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
    
    - name: Update yum cache
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat"
  
  roles:
    - common
    - docker
    - monitoring
    - security

---
- name: Deploy Flextime Application
  hosts: app_servers
  become: true
  gather_facts: true
  
  vars_files:
    - "vars/{{ environment }}.yml"
    - "vars/secrets.yml"
  
  roles:
    - app_deploy
    - nginx
    - ssl_certificates

---
- name: Configure Database Servers
  hosts: db_servers
  become: true
  gather_facts: true
  
  vars_files:
    - "vars/{{ environment }}.yml"
    - "vars/secrets.yml"
  
  roles:
    - postgresql
    - database_backup

---
- name: Configure Redis Servers
  hosts: redis_servers
  become: true
  gather_facts: true
  
  vars_files:
    - "vars/{{ environment }}.yml"
    - "vars/secrets.yml"
  
  roles:
    - redis
    - redis_sentinel